# Generated by Django 5.1.4 on 2024-12-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accaunt', '0002_courier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courier',
            options={'ordering': ['user__phone_number'], 'verbose_name': 'Courier', 'verbose_name_plural': 'Couriers'},
        ),
        migrations.AlterField(
            model_name='courier',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('bike', 'Bike'), ('car', 'Car'), ('scooter', 'Scooter')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
